artifacts {
    archives tasks.jar
    archives tasks.sourcesJar
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            groupId = project.group
            artifactId = project.name
            version = project.version

            from components.java

            artifact sourcesJar
        }
    }
    repositories {
        def MAVEN_URL = System.getenv("MAVEN_URL")
        if (MAVEN_URL != null) {
            maven {
                url MAVEN_URL
                credentials {
                    username System.getenv("MAVEN_USERNAME")
                    password System.getenv("MAVEN_PASSWORD")
                }
            }
        } else {
            maven {
                url "file://${project.projectDir}/repo"
            }
            mavenLocal()
        }
    }
}
