# Jvm info
java_version=21
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Environment info
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.238
neo_version_range=[21.1.238,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Upload info
upload=false
modrinth_id=xxxxx
curseforge_id=xxxxx

# Mod info
mod_id=anvilcraft_terminal_plugins
mod_name=AnvilCraft-TerminalPlugins
mod_license=LGPL-3.0-or-later
mod_version=1.7.2
maven_group=dev.anvilcraft.addon
mod_authors=AnvilCraft-TerminalPlugins Contributors
mod_description=Terminal plugin (upgrade module) system for AnvilCraft: installable plugins for the local / shulker / hyperdimension terminals, plus a plugin installation station.
