[versions]
minecraft = "1.21.1"
neoForge = "21.1.248"
anvillib = "2.0.0+snapshot.521"
anvilcraft = "1.6.0+snapshot.2270"
modDevGradle = "2.0.142"
lombok = "8.7.1"

[libraries]
anvillib = { group = "dev.anvilcraft.lib", name = "anvillib-neoforge-1.21.1", version.ref = "anvillib" }
anvilcraft = { group = "dev.dubhe", name = "anvilcraft-neoforge-1.21.1", version.ref = "anvilcraft" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
